export const skills = [
    "Teamwork",
    "React",
    "React Router",
    "React Hooks",
    "Redux (Toolkit)",
    "Redux-Saga",
    "Working with API (fetch, Axios)",
    "Error handling",
    "JavaScript: ES6+",
    "Promises, Async/Await",
    "Immutability",
    "Semantic & accessible HTML",
    "Responsive Web Design",
    "CSS Grid",
    "CSS Flexbox",
    "CSS animations",
    "CSS BEM convention",
    "NPM",
    "Git",
    "GitHub (Pull requests)",
    "Trello",
    "Markdown",
    "Symfony",
    "PHP 8",
    "MySQL",
];

export const skillsToLearn = [
    "TypeScript",
    "Node.js",
    "Unit testing",
    "Vue.js",
];