const skills = [
    "React",
    "JavaScript: ES6+",
    "Semantic & accessible HTML",
    "Responsive Web Design",
    "Markdown",
    "Immutability",
    "CSS BEM convention",
    "CSS Grid",
    "CSS Flexbox",
    "Teamwork",
    "React Router",
    "Redux (Toolkit)",
    "Redux-Saga",
    "React Hooks",
    "Working with API",
    "Promises, Async/Await",
    "Symfony",
    "PHP 8",
    "MySQL",
    "NPM",
    "Git",
];

export default skills;